apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-cluster
  region: u-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 4
    ssh: # use existing EC2 key
      publicKeyName: eksKey